name: Coverage Artifact

on: push

env:
  COVERAGE_FILE_NAME: coverage_file
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Run coverage
        run: npm run coverage

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.COVERAGE_FILE_NAME }}
          path: coverage/

  display-coverage:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download coverage artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.COVERAGE_FILE_NAME }}
          path: coverage/
      - name: Display coverage
        run: cat coverage/coverage-summary.json
